version: '2'
services:

    liam2-php-apache:
        build:
            context: ./php-apache
        hostname: LIAM2-Server
        ports:
            - 8080:80
            - 8044:443
        volumes:
            - LIAM2-www-data:/var/www/html
            - LIAM2-www-config:/root/config
        links:
            - 'mariadb'
        networks:
            testing_net:
                ipv4_address: 172.28.1.3

    liam2-client-php-apache:
        build:
            context: ./php-apache
        hostname: LIAM2-CLIENT
        ports:
            - 8180:80
            - 8144:443
        volumes:
            - LIAM2-CLIENT-www-data:/var/www/html
            - LIAM2-CLIENT-www-config:/root/config
        networks:
            testing_net:
                ipv4_address: 172.28.1.4


    coms-php-apache:
        build:
            context: ./php-apache   
        hostname: COMS-Server
        ports:
            - 8280:80
            - 8244:443
        volumes:
            - COMS-www-data:/var/www/html
            - COMS-www-config:/root/config
        links:
            - 'mariadb'
        networks:
            testing_net:
                ipv4_address: 172.28.1.1
            
    coms-client2-php-apache:
        build:
            context: ./php-apache
        hostname: COMS-CLIENT2
        ports:
            - 8380:80
            - 8344:443
        volumes:
            - COMS-CLIENT2-www-data:/var/www/html
            - COMS-CLIENT2-www-config:/root/config
        networks:
            testing_net:
                ipv4_address: 172.28.1.2


         
    mariadb:
        image: mariadb:10.1
        hostname: MARIADB-Server
        ports:
            - 63366:3306
        volumes:
            - mariadb:/var/lib/mysql
            - mariadb_config:/root/config
        environment:
            TZ: "Europe/Rome"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "BPMSpaceTEST"
        entrypoint:
            sh -c "echo '
            CREATE DATABASE IF NOT EXISTS bpmspace_liam2_v2;
            CREATE DATABASE IF NOT EXISTS bpmspace_coms_v1;
            ' > /docker-entrypoint-initdb.d/init.sql ;
            /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        networks:
            testing_net:
                ipv4_address: 172.28.1.10

volumes:
    mariadb:
        external:
            name: TEST-mariadb-data
    mariadb_config:
        external:
            name: TEST-mariadb-config
    
    COMS-www-data:
        external:
            name: TEST-COMS-www-data
    COMS-www-config:
        external:
            name: TEST-COMS-www-config
            
    COMS-CLIENT2-www-data:
        external:
            name: TEST-COMS-CLIENT2-www-data
    COMS-CLIENT2-www-config:
        external:
            name: TEST-COMS-CLIENT2-www-config
            
    LIAM2-www-data:
        external:
            name: TEST-LIAM2-www-data
    LIAM2-www-config:
        external:
            name: TEST-LIAM2-www-config
            
    LIAM2-CLIENT-www-data:
        external:
            name: TEST-LIAM2-CLIENT-www-data
    LIAM2-CLIENT-www-config:
        external:
            name: TEST-LIAM2-CLIENT-www-config

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16